<html>
  
  <head>
 
       <title>FR BD TV</title>
    
    <meta content="width=device-width, initial-scale=1" name="viewport" />
   
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     
   <link rel="stylesheet" href="playerjs.css">
	
<script src="https://mdfardin857875557.github.io/nice-JS-PLAY/playerjs.js" type="text/javascript"></script>	

    </head>
<body>
   
 <!--nav><center><img src="" height="50px" width="256px"></center></nav-->
    
  <main>
    
    <div id="channels">
 

</div>




		
       
</div>
       
<div id="player">
</div>
  
  </main>
<script>var player = new Playerjs({id:"player", file:'https://www.googleapis.com/drive/v3/files/1JGjGHZM8pxIoBmvMTR9kF0AHviXgbkYr?alt=media&key=AIzaSyDJGujYqxBtgIoxzyHf3Noe-fluBcKemeM', poster:"https://i.ibb.co/YRWVDrQ/images-53.jpg"});</script>


<script>
	var coll = document.getElementsByClassName("category");
	var i;

	for (i = 0; i < coll.length; i++) {
	coll[i].addEventListener("click", function() {
		this.classList.toggle("active");
		var content = this.nextElementSibling;
		if (content.style.maxHeight){
		content.style.maxHeight = null;
		} else {
		content.style.maxHeight = content.scrollHeight + "px";
		} 
	});
	}
    function play(file) {
        try {
            player.api('file',file);
            player.api('play');
            if (screen.width < 641) {
                window.scroll({
                top: 0,
                left: 0,
                behavior: 'smooth'
                });
            }
        }
        catch(err) {
            alert(err);
        }
    }
</script>
<style>
     @import url('//fonts.googleapis.com/css2?family=PT+Sans:wght@700&display=swap');

* {
    margin: 0;
    padding: 0;
    font-family: 'PT Sans', sans-serif;
}

html {
    scroll-behavior: smooth;
}

nav {
    color: red;
    height: 40px;
    padding: 0 10px;
    font-size: clamp(1.5rem, 2.0vw, 4rem); 
    background-color: #000;
    display: flex;
    justify-content: center;
    flex-direction: column;
    border: 2px solid rgb(48, 25, 52);
}

body {
    background-color: #000;
    overflow-y: hidden;
}

main {
    margin-left: 0px;
    margin-right: 0px;
    display: flex;
}

#channels {
    flex: 25.8%;
    background-color: #000;
    max-height: 100vh;
    overflow-y: scroll;
    margin-top: 3px;
    margin-left: 0px;
    overflow-x: hidden;
   scrollbar-width:thin; 
}
.channel_collapse {
    margin-top: 0px;
    max-height: 10000000px;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
    display: flex;  
    flex-wrap: wrap;
    justify-content: space-evenly;
}
#player {
    flex:100%;
    margin: auto 0px;
    margin-top: 0px;
    margin-left: 2px;
   
}
.section-title {
    width: 100%;
    color: #fff;
    background-color: #000;
    padding: 10px;
    border-bottom: solid 5px rb(229, 238, 238);
    font-size: 30px;
    font-weight: bold;
    margin-left: -1px;
}


.active:after {
  content: "";
}
::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 4px rgba(0,0,0,0.2);
	background-color: #F5f5F5;
}

::-webkit-scrollbar
{
	width: 0px;
	background-color: #F5F5F5;
}

::-webkit-scrollbar-thumb
{
	border-radius: 5px;
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
	background-color: #CC3333;
}

.channel {
    
    box-shadow: (99, 99, 99, 0.2) 0px 2px 8px 8px;
    margin-bottom: 10px;
    margin-right: 10px;
    border-radius: 10px;
    overflow: hidden;
    padding: 1px;
    cursor: pointer; 
    color:#fff;
    font-size:1px;
    text-align: center;
        
}

.channel p {font-size:0px; text-align: center; margin-top: 1px;color:#fff}

.channel:active {
    animation: press 0.2s 1 linear;
}


.channel img {
    width: 100px;
    height: 100px;
    border: 4px solid green;
    border-radius: 100px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 200px 0 rgba(0, 0, 0, 0.19);
}

@media only screen and (max-width: 640px) {
    nav {
        text-align: center;
    }
    main {
        flex-direction: column-reverse;
    }
    body {
        overflow-y: auto;
    }
    #channels {
        height: fit-content;
        overflow-y: unset;
        margin-left: 5px;
        margin-right: 5px;
    }
    .channel {
        margin-right: 0;
    }
    #player {
        flex: auto;
       min-width: 192px;
       min-height: 108px;
       margin-left: 5px;
       margin-right: 5px;
       margin-bottom: 5px;
    }
}

@keyframes press {
    0% {
        transform: scale(1);
    }
    50% {
        transform: scale(0.92);
    }
    to {
        transform: scale(1);
    }
}
</style>





</body>
</html>
